version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    container_name: freak-bank-db
    environment:
      - POSTGRES_USER=${DB_USERNAME:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-123456}
      - POSTGRES_DB=${DB_DATABASE:-fbank}
    ports:
      - "5432:5432"