// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64            `json:"id"`
	Owner     string           `json:"owner"`
	Balance   int64            `json:"balance"`
	Currency  string           `json:"currency"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Entry struct {
	ID        int64            `json:"id"`
	AccountID pgtype.Int8      `json:"account_id"`
	Amount    int64            `json:"amount"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Transfer struct {
	ID            int64            `json:"id"`
	FromAccountID pgtype.Int8      `json:"from_account_id"`
	ToAccountID   pgtype.Int8      `json:"to_account_id"`
	Amount        int64            `json:"amount"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type User struct {
	Username          string           `json:"username"`
	HashedPassword    string           `json:"hashed_password"`
	FullName          string           `json:"full_name"`
	Email             string           `json:"email"`
	PasswordChangedAt pgtype.Timestamp `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}
